// daycare_care.jsx — daily care logs, incidents, and operational reports.
const { useState: useStateDcc } = React;

function DccLogForm({ children, onClose, onSaved }) {
  const [form,setForm]=useStateDcc({child_id:children[0]&&children[0].id||"",log_date:window.DcxToday(),occurred_at:new Date().toISOString().slice(0,16),activity:"",mood:"",meal:"",nap_minutes:"",bathroom:"",notes:""});const [busy,setBusy]=useStateDcc(false);const [error,setError]=useStateDcc("");
  const save=async()=>{if(!form.child_id){setError("Choose a child.");return;}setBusy(true);try{await window.DcxRequest("/log/save",{body:{log:{...form,nap_minutes:form.nap_minutes===""?null:Number(form.nap_minutes)}}});onSaved();}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <window.DcxModal wide title="Add daily care log" copy="Families see approved care information in the shared app." onClose={onClose}>{error&&<div className="dc-form-error">{error}</div>}<div className="dc-form-grid"><window.DcxField label="Child"><select value={form.child_id} onChange={(e)=>setForm({...form,child_id:e.target.value})}>{children.map((child)=><option key={child.id} value={child.id}>{window.DcxChildName(child)}</option>)}</select></window.DcxField><window.DcxField label="Date"><input type="date" value={form.log_date} onChange={(e)=>setForm({...form,log_date:e.target.value})}/></window.DcxField><window.DcxField label="Activity"><input value={form.activity} onChange={(e)=>setForm({...form,activity:e.target.value})} placeholder="Outdoor play, reading…"/></window.DcxField><window.DcxField label="Mood"><select value={form.mood} onChange={(e)=>setForm({...form,mood:e.target.value})}><option value="">Not recorded</option><option>Happy</option><option>Calm</option><option>Tired</option><option>Upset</option><option>Energetic</option></select></window.DcxField><window.DcxField label="Meal"><input value={form.meal} onChange={(e)=>setForm({...form,meal:e.target.value})} placeholder="Ate all / some / none"/></window.DcxField><window.DcxField label="Nap minutes"><input type="number" min="0" value={form.nap_minutes} onChange={(e)=>setForm({...form,nap_minutes:e.target.value})}/></window.DcxField><window.DcxField label="Bathroom"><input value={form.bathroom} onChange={(e)=>setForm({...form,bathroom:e.target.value})}/></window.DcxField><window.DcxField label="Notes" wide><textarea rows="3" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></window.DcxField></div><div className="dc-modal-actions"><button className="dc-quiet" onClick={onClose}>Cancel</button><button className="dc-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save daily log"}</button></div></window.DcxModal>;
}

function DaycareCareLogs() {
  const [from,setFrom]=useStateDcc(window.DcxToday()); const [to,setTo]=useStateDcc(window.DcxToday());const [adding,setAdding]=useStateDcc(false);
  const logsResource=window.DcxUseResource("/logs?from="+encodeURIComponent(from)+"&to="+encodeURIComponent(to),"logs",15000);const childrenResource=window.DcxUseResource("/children","children",30000);const logs=Array.isArray(logsResource.data)?logsResource.data:[];const children=Array.isArray(childrenResource.data)?childrenResource.data:[];
  const childName=(id)=>window.DcxChildName(children.find((child)=>child.id===id));
  return <div className="dc-page"><window.DcxPageHead title="Daily Care Logs" eyebrow="CARE & FAMILY VISIBILITY" copy="Meals, naps, moods, activities, bathroom notes, and daily context." actions={<><div className="dc-date-range"><input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/><span>to</span><input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></div><button className="dc-primary" disabled={!children.length} onClick={()=>setAdding(true)}><window.Icons.Plus size={14}/> Add care log</button></>}/><window.DcxState loading={logsResource.loading||childrenResource.loading} error={logsResource.error||childrenResource.error} onRetry={()=>{logsResource.refresh();childrenResource.refresh();}} empty={!logs.length} icon="CareLogs" title="No care logs in this range" copy="Choose another date or add the first daily update.">{children.length?<button className="dc-primary" onClick={()=>setAdding(true)}>Add care log</button>:<button className="dc-primary" onClick={()=>window.GoTo("Enrollment")}>Enroll a child first</button>}</window.DcxState>{logs.length>0&&<div className="dc-log-grid">{logs.map((log)=><article className="card card-pad dc-log-card" key={log.id}><div className="dc-log-head"><div className="dc-person"><div className="dc-avatar">{childName(log.child_id).slice(0,1)}</div><div><b>{childName(log.child_id)}</b><small>{window.DcxDate(log.occurred_at||log.log_date,true)}</small></div></div><span className="dc-status">Daily log</span></div><div className="dc-care-metrics">{log.mood&&<span><small>Mood</small><b>{log.mood}</b></span>}{log.meal&&<span><small>Meal</small><b>{log.meal}</b></span>}{log.nap_minutes!=null&&<span><small>Nap</small><b>{log.nap_minutes} min</b></span>}{log.bathroom&&<span><small>Bathroom</small><b>{log.bathroom}</b></span>}</div>{log.activity&&<p><b>Activity:</b> {log.activity}</p>}{log.notes&&<p>{log.notes}</p>}</article>)}</div>}{adding&&<DccLogForm children={children} onClose={()=>setAdding(false)} onSaved={()=>{setAdding(false);logsResource.refresh();}}/>}</div>;
}

function DccIncidentForm({ children, onClose, onSaved }) {
  const [form,setForm]=useStateDcc({child_id:children[0]&&children[0].id||"",occurred_at:new Date().toISOString().slice(0,16),location_detail:"",severity:"minor",description:"",action_taken:"",parent_notified:false});const [busy,setBusy]=useStateDcc(false);const [error,setError]=useStateDcc("");
  const save=async()=>{if(!form.child_id||!form.description.trim()||!form.action_taken.trim()){setError("Child, description, and action taken are required.");return;}setBusy(true);try{await window.DcxRequest("/incident/save",{body:{incident:{...form,parent_notified_at:form.parent_notified?new Date().toISOString():null}}});onSaved();}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <window.DcxModal wide title="Record incident" copy="Create a complete, permanent safety record." onClose={onClose}>{error&&<div className="dc-form-error">{error}</div>}<div className="dc-form-grid"><window.DcxField label="Child"><select value={form.child_id} onChange={(e)=>setForm({...form,child_id:e.target.value})}>{children.map((child)=><option key={child.id} value={child.id}>{window.DcxChildName(child)}</option>)}</select></window.DcxField><window.DcxField label="Occurred at"><input type="datetime-local" value={form.occurred_at} onChange={(e)=>setForm({...form,occurred_at:e.target.value})}/></window.DcxField><window.DcxField label="Location detail"><input value={form.location_detail} onChange={(e)=>setForm({...form,location_detail:e.target.value})} placeholder="Playground, classroom…"/></window.DcxField><window.DcxField label="Severity"><select value={form.severity} onChange={(e)=>setForm({...form,severity:e.target.value})}><option value="minor">Minor</option><option value="moderate">Moderate</option><option value="serious">Serious</option></select></window.DcxField><window.DcxField label="Description *" wide><textarea rows="3" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></window.DcxField><window.DcxField label="Action taken *" wide><textarea rows="3" value={form.action_taken} onChange={(e)=>setForm({...form,action_taken:e.target.value})}/></window.DcxField><window.DcxField label="Family notification" wide><label className="dc-switch-row"><input type="checkbox" checked={form.parent_notified} onChange={(e)=>setForm({...form,parent_notified:e.target.checked})}/><span>Parent / guardian was notified</span></label></window.DcxField></div><div className="dc-form-hint warn"><window.Icons.AlertTriangle size={14}/> Review details carefully. Incident records are not silently discarded after saving.</div><div className="dc-modal-actions"><button className="dc-quiet" onClick={onClose}>Cancel</button><button className="dc-primary" disabled={busy} onClick={save}>{busy?"Recording…":"Record incident"}</button></div></window.DcxModal>;
}

function DaycareIncidents() {
  const [from,setFrom]=useStateDcc(()=>{const date=new Date();date.setDate(date.getDate()-30);return date.toISOString().slice(0,10);});const [to,setTo]=useStateDcc(window.DcxToday());const [adding,setAdding]=useStateDcc(false);
  const incidentsResource=window.DcxUseResource("/incidents?from="+encodeURIComponent(from)+"&to="+encodeURIComponent(to),"incidents",15000);const childrenResource=window.DcxUseResource("/children","children",30000);const incidents=Array.isArray(incidentsResource.data)?incidentsResource.data:[];const children=Array.isArray(childrenResource.data)?childrenResource.data:[];const childName=(id)=>window.DcxChildName(children.find((child)=>child.id===id));
  return <div className="dc-page"><window.DcxPageHead title="Incident Records" eyebrow="SAFETY & COMPLIANCE" copy="Review and record center incidents with family notification status." actions={<><div className="dc-date-range"><input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/><span>to</span><input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></div><button className="dc-primary" disabled={!children.length} onClick={()=>setAdding(true)}><window.Icons.Plus size={14}/> Record incident</button></>}/><window.DcxState loading={incidentsResource.loading||childrenResource.loading} error={incidentsResource.error||childrenResource.error} onRetry={()=>{incidentsResource.refresh();childrenResource.refresh();}} empty={!incidents.length} icon="Incidents" title="No incidents in this range" copy="That’s good news. New safety records will appear here."></window.DcxState>{incidents.length>0&&<div className="card dc-table-wrap"><table className="lead-table dc-table"><thead><tr><th>Occurred</th><th>Child</th><th>Severity</th><th>Location</th><th>Description & action</th><th>Family notified</th></tr></thead><tbody>{incidents.map((incident)=><tr key={incident.id}><td>{window.DcxDate(incident.occurred_at,true)}</td><td><b>{childName(incident.child_id)}</b></td><td><span className={"dc-severity-pill "+(incident.severity||"minor")}>{incident.severity||"minor"}</span></td><td>{incident.location_detail||"—"}</td><td className="dc-long-cell"><b>{incident.description}</b><small>{incident.action_taken}</small></td><td>{incident.parent_notified_at?<span className="dc-status">{window.DcxDate(incident.parent_notified_at,true)}</span>:<span className="dc-status warn">Not recorded</span>}</td></tr>)}</tbody></table></div>}{adding&&<DccIncidentForm children={children} onClose={()=>setAdding(false)} onSaved={()=>{setAdding(false);incidentsResource.refresh();}}/>}</div>;
}

function DaycareReports() {
  const [from,setFrom]=useStateDcc(()=>{const d=new Date();d.setDate(1);return d.toISOString().slice(0,10);});const [to,setTo]=useStateDcc(window.DcxToday());const reportResource=window.DcxUseResource("/reports?from="+encodeURIComponent(from)+"&to="+encodeURIComponent(to),"reports",30000);const report=reportResource.data||{};const metrics=report.metrics||report;
  return <div className="dc-page"><window.DcxPageHead title="Operational Reports" copy="A management snapshot generated from live center records." actions={<div className="dc-date-range"><input type="date" value={from} onChange={(e)=>setFrom(e.target.value)}/><span>to</span><input type="date" value={to} onChange={(e)=>setTo(e.target.value)}/></div>}/><window.DcxState loading={reportResource.loading} error={reportResource.error} onRetry={reportResource.refresh}><><div className="dc-kpi-grid"><window.DcxKpi label="Attendance Rate" value={Math.round(Number(metrics.attendance_rate||0))+"%"} sub="scheduled days present" icon="Attendance" color="#22C55E"/><window.DcxKpi label="Avg. Occupancy" value={Math.round(Number(metrics.occupancy_rate||0))+"%"} sub="licensed capacity" icon="Classrooms"/><window.DcxKpi label="Incidents" value={Number(metrics.incident_count||0)} sub="recorded in range" icon="Incidents" color="#F4B860"/><window.DcxKpi label="Collected" value={window.DcxMoney(metrics.amount_collected||0)} sub="payments in range" icon="Billing" color="#22C55E"/></div><div className="dc-report-grid"><div className="card card-pad"><div className="dc-report-icon"><window.Icons.Attendance size={20}/></div><h3>Attendance</h3><p>{Number(metrics.attendance_days||0)} child-days recorded across the selected dates.</p><button className="link" onClick={()=>window.GoTo("Attendance")}>Open attendance</button></div><div className="card card-pad"><div className="dc-report-icon"><window.Icons.Children size={20}/></div><h3>Enrollment & capacity</h3><p>{Number(metrics.children_active||0)} active children across {Number(metrics.classrooms_active||0)} classrooms.</p><button className="link" onClick={()=>window.GoTo("Classrooms")}>Review capacity</button></div><div className="card card-pad"><div className="dc-report-icon"><window.Icons.Staff size={20}/></div><h3>Staff coverage</h3><p>{Number(metrics.staff_active||0)} active team members; {Number(metrics.hours_worked||0).toFixed(1)} hours recorded.</p><button className="link" onClick={()=>window.GoTo("Staff")}>Review schedules</button></div><div className="card card-pad"><div className="dc-report-icon"><window.Icons.Billing size={20}/></div><h3>Billing health</h3><p>{window.DcxMoney(metrics.amount_due||0)} outstanding across {Number(metrics.invoices_due||0)} invoices.</p><button className="link" onClick={()=>window.GoTo("Billing")}>Open billing</button></div></div></></window.DcxState></div>;
}

Object.assign(window,{DaycareCareLogs,DaycareIncidents,DaycareReports});
