// daycare_finance.jsx — record-based invoices, payments, payroll.
const { useState: useStateDcf } = React;

function DcfInvoiceForm({ children, directory, invoice, onClose, onSaved }) {
  const guardians=directory.filter((profile)=>profile.role==="parent");const [form,setForm]=useStateDcf(invoice?{...invoice}:{guardian_id:guardians[0]&&guardians[0].id||"",child_id:"",description:"Tuition",amount:"",issued_on:window.DcxToday(),due_on:window.DcxToday(),status:"due"});const [busy,setBusy]=useStateDcf(false);const [error,setError]=useStateDcf("");
  const save=async()=>{if(!form.guardian_id||!form.description.trim()||Number(form.amount)<=0){setError("Guardian, description, and a positive amount are required.");return;}setBusy(true);try{await window.DcxRequest("/invoice/save",{body:{invoice:{...form,amount:Number(form.amount)}}});onSaved();}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <window.DcxModal title={invoice?"Edit invoice":"Create invoice"} copy="This records an amount due; it does not charge a card." onClose={onClose}>{error&&<div className="dc-form-error">{error}</div>}<div className="dc-form-grid"><window.DcxField label="Guardian"><select value={form.guardian_id} onChange={(e)=>setForm({...form,guardian_id:e.target.value})}><option value="">Choose guardian</option>{guardians.map((profile)=><option key={profile.id} value={profile.id}>{window.DcxName(profile)}</option>)}</select></window.DcxField><window.DcxField label="Child"><select value={form.child_id||""} onChange={(e)=>setForm({...form,child_id:e.target.value})}><option value="">Family account</option>{children.map((child)=><option key={child.id} value={child.id}>{window.DcxChildName(child)}</option>)}</select></window.DcxField><window.DcxField label="Description" wide><input value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></window.DcxField><window.DcxField label="Amount"><input type="number" min="0.01" step="0.01" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})}/></window.DcxField><window.DcxField label="Status"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="due">Due</option><option value="void">Void</option></select></window.DcxField><window.DcxField label="Issued on"><input type="date" value={form.issued_on} onChange={(e)=>setForm({...form,issued_on:e.target.value})}/></window.DcxField><window.DcxField label="Due on"><input type="date" value={form.due_on} onChange={(e)=>setForm({...form,due_on:e.target.value})}/></window.DcxField></div><div className="dc-form-hint"><window.Icons.Shield size={14}/> Stripe-ready records are used, but no card is charged in this phase.</div><div className="dc-modal-actions"><button className="dc-quiet" onClick={onClose}>Cancel</button><button className="dc-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save invoice"}</button></div></window.DcxModal>;
}

function DcfPaymentForm({ invoice, onClose, onSaved }) {
  const paid=(invoice.payments||[]).reduce((sum,payment)=>sum+(Number(payment.amount)||0),0);const remaining=Math.max(0,Number(invoice.amount)-paid);const [form,setForm]=useStateDcf({amount:remaining,method_label:"Cash",paid_at:new Date().toISOString().slice(0,16),reference:"",provider:"manual"});const [busy,setBusy]=useStateDcf(false);const [error,setError]=useStateDcf("");
  const save=async()=>{if(Number(form.amount)<=0||Number(form.amount)>remaining){setError("Enter a payment no greater than the remaining balance.");return;}setBusy(true);try{await window.DcxRequest("/invoice/record-payment",{body:{invoice_id:invoice.id,payment:{...form,amount:Number(form.amount)}}});onSaved();}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <window.DcxModal title="Record manual payment" copy={(invoice.invoice_number||"Invoice")+" · "+window.DcxMoney(remaining)+" remaining"} onClose={onClose}>{error&&<div className="dc-form-error">{error}</div>}<div className="dc-form-grid"><window.DcxField label="Amount"><input autoFocus type="number" min="0.01" max={remaining} step="0.01" value={form.amount} onChange={(e)=>setForm({...form,amount:e.target.value})}/></window.DcxField><window.DcxField label="Method"><select value={form.method_label} onChange={(e)=>setForm({...form,method_label:e.target.value})}><option>Cash</option><option>Check</option><option>Bank transfer</option><option>External card payment</option><option>Other</option></select></window.DcxField><window.DcxField label="Paid at"><input type="datetime-local" value={form.paid_at} onChange={(e)=>setForm({...form,paid_at:e.target.value})}/></window.DcxField><window.DcxField label="Reference"><input value={form.reference} onChange={(e)=>setForm({...form,reference:e.target.value})} placeholder="Check # / external ref"/></window.DcxField></div><div className="dc-form-hint warn"><window.Icons.Dollar size={14}/> Only record money already received. This action does not move funds.</div><div className="dc-modal-actions"><button className="dc-quiet" onClick={onClose}>Cancel</button><button className="dc-primary" disabled={busy} onClick={save}>{busy?"Recording…":"Record payment"}</button></div></window.DcxModal>;
}

function DaycareBilling() {
  const billingResource=window.DcxUseResource("/billing","billing",15000);const childrenResource=window.DcxUseResource("/children","children",30000);const [modal,setModal]=useStateDcf(null);const [payment,setPayment]=useStateDcf(null);const billing=billingResource.data||{};const invoices=Array.isArray(billing)?billing:Array.isArray(billing.invoices)?billing.invoices:[];const directory=Array.isArray(billing.directory)?billing.directory:[];const children=Array.isArray(childrenResource.data)?childrenResource.data:[];
  const total=invoices.reduce((sum,item)=>sum+(Number(item.amount)||0),0);const paid=invoices.reduce((sum,item)=>sum+(item.payments||[]).reduce((acc,p)=>acc+(Number(p.amount)||0),0),0);const due=Math.max(0,total-paid);
  return <div className="dc-page"><window.DcxPageHead title="Billing" eyebrow="RECORD-BASED FINANCE" copy="Invoices and manual payment records—no cards are charged here." actions={<button className="dc-primary" onClick={()=>setModal("new")}><window.Icons.Plus size={14}/> Create invoice</button>}/><div className="dc-kpi-grid"><window.DcxKpi label="Invoice Total" value={window.DcxMoney(total)} sub="all visible invoices" icon="Billing"/><window.DcxKpi label="Collected" value={window.DcxMoney(paid)} sub="recorded payments" icon="Dollar" color="#22C55E"/><window.DcxKpi label="Outstanding" value={window.DcxMoney(due)} sub="remaining balances" icon="AlertTriangle" color="#F4B860"/><window.DcxKpi label="Open Invoices" value={invoices.filter((item)=>item.status!=="paid"&&item.status!=="void").length} sub="needs follow-up" icon="Doc" color="#8B5CF6"/></div><window.DcxState loading={billingResource.loading||childrenResource.loading} error={billingResource.error||childrenResource.error} onRetry={()=>{billingResource.refresh();childrenResource.refresh();}} empty={!invoices.length} icon="Billing" title="No invoices yet" copy="Create a tuition or fee record when a family owes a balance."><button className="dc-primary" onClick={()=>setModal("new")}>Create first invoice</button></window.DcxState>{invoices.length>0&&<div className="card dc-table-wrap"><table className="lead-table dc-table"><thead><tr><th>Invoice</th><th>Family / child</th><th>Issued</th><th>Due</th><th>Amount</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>{invoices.map((invoice)=>{const invoicePaid=(invoice.payments||[]).reduce((sum,p)=>sum+(Number(p.amount)||0),0);const balance=Math.max(0,Number(invoice.amount)-invoicePaid);return <tr key={invoice.id}><td><b>{invoice.invoice_number||"Invoice"}</b><small>{invoice.description}</small></td><td>{invoice.guardian_name||window.DcxName(invoice.guardian,"Family account")}<small>{invoice.children?window.DcxChildName(invoice.children):""}</small></td><td>{window.DcxDate(invoice.issued_on)}</td><td>{window.DcxDate(invoice.due_on)}</td><td className="tabnum">{window.DcxMoney(invoice.amount)}</td><td className="tabnum"><b>{window.DcxMoney(balance)}</b></td><td><span className={"dc-finance-status "+(balance===0?"paid":invoice.status)}>{balance===0?"paid":invoice.status}</span></td><td><div className="dc-row-actions"><button onClick={()=>setModal(invoice)}>Edit</button>{balance>0&&invoice.status!=="void"&&<button onClick={()=>setPayment(invoice)}>Record payment</button>}</div></td></tr>;})}</tbody></table></div>}{modal&&<DcfInvoiceForm children={children} directory={directory} invoice={modal==="new"?null:modal} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);billingResource.refresh();}}/>}{payment&&<DcfPaymentForm invoice={payment} onClose={()=>setPayment(null)} onSaved={()=>{setPayment(null);billingResource.refresh();}}/>}</div>;
}

function DcfPayrollForm({ staff, payroll, onClose, onSaved }) {
  const [form,setForm]=useStateDcf(payroll?{...payroll}:{staff_id:staff[0]&&staff[0].id||"",period_start:window.DcxToday(),period_end:window.DcxToday(),regular_hours:"",overtime_hours:0,gross_pay:"",deductions:0,net_pay:"",status:"draft"});const [busy,setBusy]=useStateDcf(false);const [error,setError]=useStateDcf("");
  const update=(key,value)=>{const next={...form,[key]:value};if(["gross_pay","deductions"].includes(key))next.net_pay=Math.max(0,Number(next.gross_pay||0)-Number(next.deductions||0));setForm(next);};
  const save=async()=>{if(!form.staff_id||!form.period_start||!form.period_end||Number(form.net_pay)<0){setError("Staff, pay period, and valid totals are required.");return;}setBusy(true);try{await window.DcxRequest("/payroll/save",{body:{payroll:{...form,regular_hours:Number(form.regular_hours||0),overtime_hours:Number(form.overtime_hours||0),gross_pay:Number(form.gross_pay||0),deductions:Number(form.deductions||0),net_pay:Number(form.net_pay||0)}}});onSaved();}catch(requestError){setError(requestError.message);}finally{setBusy(false);}};
  return <window.DcxModal title={payroll?"Edit payroll record":"Create payroll record"} copy="This tracks payroll status; it does not transfer money." onClose={onClose}>{error&&<div className="dc-form-error">{error}</div>}<div className="dc-form-grid"><window.DcxField label="Team member"><select value={form.staff_id} onChange={(e)=>setForm({...form,staff_id:e.target.value})}>{staff.map((member)=><option key={member.id} value={member.id}>{window.DcxName(member)}</option>)}</select></window.DcxField><window.DcxField label="Status"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="approved">Approved</option></select></window.DcxField><window.DcxField label="Period start"><input type="date" value={form.period_start} onChange={(e)=>setForm({...form,period_start:e.target.value})}/></window.DcxField><window.DcxField label="Period end"><input type="date" value={form.period_end} onChange={(e)=>setForm({...form,period_end:e.target.value})}/></window.DcxField><window.DcxField label="Regular hours"><input type="number" min="0" step="0.25" value={form.regular_hours} onChange={(e)=>update("regular_hours",e.target.value)}/></window.DcxField><window.DcxField label="Overtime hours"><input type="number" min="0" step="0.25" value={form.overtime_hours} onChange={(e)=>update("overtime_hours",e.target.value)}/></window.DcxField><window.DcxField label="Gross pay"><input type="number" min="0" step="0.01" value={form.gross_pay} onChange={(e)=>update("gross_pay",e.target.value)}/></window.DcxField><window.DcxField label="Deductions"><input type="number" min="0" step="0.01" value={form.deductions} onChange={(e)=>update("deductions",e.target.value)}/></window.DcxField><window.DcxField label="Net pay"><input type="number" min="0" step="0.01" value={form.net_pay} onChange={(e)=>update("net_pay",e.target.value)}/></window.DcxField></div><div className="dc-form-hint warn"><window.Icons.Dollar size={14}/> Saving or marking paid records status only; FORGE does not transfer payroll funds.</div><div className="dc-modal-actions"><button className="dc-quiet" onClick={onClose}>Cancel</button><button className="dc-primary" disabled={busy} onClick={save}>{busy?"Saving…":"Save payroll"}</button></div></window.DcxModal>;
}

function DaycarePayroll() {
  const payrollResource=window.DcxUseResource("/payroll","payroll",15000);const staffResource=window.DcxUseResource("/staff","staff",30000);const payroll=Array.isArray(payrollResource.data)?payrollResource.data:[];const staff=Array.isArray(staffResource.data)?staffResource.data:[];const [modal,setModal]=useStateDcf(null);const [confirm,setConfirm]=useStateDcf(null);
  const markPaid=async()=>{try{await window.DcxRequest("/payroll/record-paid",{body:{payroll_id:confirm.id,paid_at:new Date().toISOString()}});setConfirm(null);payrollResource.refresh();}catch(error){window.alert(error.message);}};
  const total=payroll.reduce((sum,item)=>sum+(Number(item.net_pay)||0),0);const pending=payroll.filter((item)=>item.status!=="paid").reduce((sum,item)=>sum+(Number(item.net_pay)||0),0);
  return <div className="dc-page"><window.DcxPageHead title="Payroll" eyebrow="RECORD-BASED FINANCE" copy="Create pay-period records and track paid status without moving funds." actions={<button className="dc-primary" disabled={!staff.length} onClick={()=>setModal("new")}><window.Icons.Plus size={14}/> New payroll record</button>}/><div className="dc-kpi-grid"><window.DcxKpi label="Payroll Total" value={window.DcxMoney(total)} sub="visible periods" icon="Payroll"/><window.DcxKpi label="Pending" value={window.DcxMoney(pending)} sub="not marked paid" icon="Dollar" color="#F4B860"/><window.DcxKpi label="Records" value={payroll.length} sub="pay periods" icon="Doc" color="#8B5CF6"/><window.DcxKpi label="Active Staff" value={staff.length} sub="eligible team" icon="Staff" color="#22C55E"/></div><window.DcxState loading={payrollResource.loading||staffResource.loading} error={payrollResource.error||staffResource.error} onRetry={()=>{payrollResource.refresh();staffResource.refresh();}} empty={!payroll.length} icon="Payroll" title="No payroll records" copy="Create a pay-period record when totals are ready.">{staff.length?<button className="dc-primary" onClick={()=>setModal("new")}>Create first record</button>:<button className="dc-primary" onClick={()=>window.GoTo("Staff")}>Add staff first</button>}</window.DcxState>{payroll.length>0&&<div className="card dc-table-wrap"><table className="lead-table dc-table"><thead><tr><th>Team member</th><th>Period</th><th>Hours</th><th>Gross</th><th>Deductions</th><th>Net pay</th><th>Status</th><th></th></tr></thead><tbody>{payroll.map((item)=><tr key={item.id}><td><b>{window.DcxName(item.staff_members||staff.find((member)=>member.id===item.staff_id))}</b></td><td>{window.DcxDate(item.period_start)} – {window.DcxDate(item.period_end)}</td><td>{Number(item.regular_hours||0)+Number(item.overtime_hours||0)}</td><td>{window.DcxMoney(item.gross_pay)}</td><td>{window.DcxMoney(item.deductions)}</td><td><b>{window.DcxMoney(item.net_pay)}</b></td><td><span className={"dc-finance-status "+item.status}>{item.status}</span></td><td><div className="dc-row-actions"><button onClick={()=>setModal(item)}>Edit</button>{item.status!=="paid"&&<button onClick={()=>setConfirm(item)}>Mark paid</button>}</div></td></tr>)}</tbody></table></div>}{modal&&<DcfPayrollForm staff={staff} payroll={modal==="new"?null:modal} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);payrollResource.refresh();}}/>}{confirm&&<window.DcxConfirm title="Mark payroll paid?" copy={window.DcxMoney(confirm.net_pay)+" will be recorded as paid now. This does not transfer money."} confirmLabel="Record paid status" onClose={()=>setConfirm(null)} onConfirm={markPaid}/>}</div>;
}

Object.assign(window,{DaycareBilling,DaycarePayroll});
